### ISSUE TITLE
Error on joyplot

### ISSUE THREAD

**Issue by Fel-1234** [asjadnaqvi/stata-ridgeline#10]
joyplot new_cases date, over(country)
invalid syntax
im getting the error

**Comment by Stata-ww** [comment]
me too。How solve it?

**Comment by asjadnaqvi** [comment]
Update the packages:

```
ssc install joyplot, replace
ssc install palettes, replace
ssc install colrspace, replace
```

and try again.

**Comment by Stata-ww** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asjadnaqvi/stata-joyplot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 下午3:41
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [asjadnaqvi/stata-joyplot] Error on joyplot (Issue #10)





 
Update the packages:
 ssc install joyplot, replace ssc install palettes, replace ssc install colrspace, replace  
and try again.
