### ISSUE TITLE
Insufficient observations r(2001) 

### ISSUE THREAD

**Issue by hhiihh** [asjadnaqvi/stata-ridgeline#12]
Hi,

Thanks for providing this package. 

I have a dataset with ~60 observations that I wish to use joyplot, but am hitting this error of having insufficient observations. This is in the context of only using one y variable (joyplot y, over(country)) to create overlapping histograms via joyplots.

Is this a known issue?

**Comment by hhiihh** [comment]
Hi, open closer inspection there was only 1 observation for a country which creates this error.

**Comment by asjadnaqvi** [comment]
Thanks! I will enchance the error message to display this information.

**Comment by asjadnaqvi** [comment]
Add errors for low observations in v1.6
