### ISSUE TITLE
Should it be "...over(country)" instead of "...by(country)"?

### ISSUE THREAD

**Issue by nanoapple** [asjadnaqvi/stata-ridgeline#15]
Not sure if the syntax rule has been changed.
When copied and pasted the following code:

`joyplot new_cases date if date > 22460, by(country) yline bwid(0.1) norm(local)`

STATA prompted: "option over() required"

Changed it to "...over(country)", and it works perfectly.

**Comment by asjadnaqvi** [comment]
The very new version (not currently on SSC) changed `over()` to `by()` (see [Change log](https://github.com/asjadnaqvi/stata-joyplot#Change-log)). I will submit it to avoid confusion with the GitHub examples.

Thanks for pointing this out!
