### ISSUE TITLE
which joyplot - date stamp update required

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-ridgeline#17]
Dear Asjad,

I have updated `joyplot` and I am able to replicate your Version 1.7 example just fine.
However, I observe that you ado version and date reference was not updated yet:
```
. which joyplot
c:\ado\plus\j\joyplot.ado
*! joyplot v1.62 (28 May 2023)
*! Asjad Naqvi (asjadnaqvi@gmail.com)
```
So, an 'optical' issue but important to comfort users of your fine package.

**Comment by asjadnaqvi** [comment]
Fixed!
