### ISSUE TITLE
Feature request: allow passing n() option to kdensity

### ISSUE THREAD

**Issue by santiago-afonso** [asjadnaqvi/stata-ridgeline#20]
The chart I'm getting from joyplot 1.71 seems "low poly", with a low number of points in the distribution. I'd be great if we could pass a higher n() than the default, even if the rendering is slow.

Thanks!!

**Comment by asjadnaqvi** [comment]
The option `n()` has been added but the rough figures might be a feature of low data points. One way to remove these is to keep increasing the bandwidth.

**Comment by santiago-afonso** [comment]
The full file has over 40 millions obs, not a problem 😄

**Comment by asjadnaqvi** [comment]
The error messages have been updated to show how many observations are left after using `droplow`. If the problem still persists open a new issue :)
