### ISSUE TITLE
ysize option

### ISSUE THREAD

**Issue by johnchin14** [asjadnaqvi/stata-ridgeline#5]
I'm trying a joyplot that shows 38 units / countries and it looks a bit too compressed (making it harder, among other things, to determine which ridgeline goes with which country). Any chance you can add the option to adjust the ysize() to be longer to alleviate this issue?

**Comment by asjadnaqvi** [comment]
xsize() and ysize() options added in v1.21 on GitHub. Here the scaling of the joyplot waves can also be controlled using the overlap() option. The default value is overlap(6). A lower value will reduce the height of the wave. This also allows for better scaling of y-axis labels.
