### ISSUE TITLE
Options for `over`

### ISSUE THREAD

**Issue by van-alfen** [asjadnaqvi/stata-ridgeline#8]
It looks like the `over` option can only accept variables that are strings or labeled numeric data. Is that the case?
For example, I would like to plot the distribution of a variable over the years.
`joyploy myvar, over(year)`
This gives me an error saying the variable **y2005** is not found.
However, if I convert year to a string variable, it works.
It also works if I encode the string variable (i.e., 1 "2005" 2 "2006" ...).
If this is by design, then a more helpful error code would be useful. But it would be great if numeric variables like *year* were allowed.
Thanks!

**Comment by asjadnaqvi** [comment]
fixed!
